### ISSUE TITLE
Ability to handle duplicate sections

### ISSUE THREAD

**Issue by Wernervdmerwe** [voxpupuli/puppet-telegraf#85] opened 2017-11-25 23:16 UTC
Agreeably this hurts the head to ponder, but seems it is a valid use case in eg [https://github.com/influxdata/telegraf/tree/master/plugins/inputs/postgresql_extensible]

If duplicates are specified as below, only the last is affected into the final configuration file

```
    sections       => {
      'postgresql_extensible.query' => {
      'sqlquery'   => 'SELECT * FROM pg_stat_database where datname',
      'version'    => 901,
      'withdbname' => true,
      'tagvalue'   => 'postgres'
      },
      'postgresql_extensible.query' => {
      'sqlquery'   => 'SELECT * FROM pg_stat_bgwriter where datname',
      'version'    => 901,
      'withdbname' => true,
      'tagvalue'   => 'postgres'
      },
    }

```

**Comment by spjmurray** [comment] 2017-11-27 18:13
Sounds like a simple job of allowing a hash or list of hashes under the section key to me. If a hash emit, if a list duplicate the key and emit, winner winner chicken dinner.  My 50 cents...

**Comment by spjmurray** [comment] 2017-11-27 18:22
```yaml
dog:
  name: 'scruffy' 
  breed: 'scotty' 
cat:
  - name: 'tiddles' 
    breed: 'siamese'
  - name: 'puss' 
    breed: 'ocelot' 
```
```
[dog]
name = scruffy
breed = scotty
[cat]
name = tiddles
breed = siamese
[cat]
name = puss
breed = ocelot
```

**Comment by sparr** [comment] 2017-12-21 19:17
I would support @spjmurray's solution. I think it is unambiguous.

**Comment by sparr** [comment] 2017-12-21 19:18
Caveat: the behavior for deep merge would need to be documented. If you already have a list and merge a hash, does the hash add to the list or replace it? If you already have a hash and merge a list, same question.

**Comment by sparr** [comment] 2017-12-21 19:22
Oh, this seems to be a duplicate of #42  which has more comments.

**Comment by yankcrime** [comment] 2018-01-18 09:35
Closing this now that #80 has been merged which should address this use case.

**Closed as completed by yankcrime** 2018-01-18 09:35 UTC
